name: numerologia
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  printing: ^5.13.2  # Versió actualitzada a la data actual
  pdf: ^3.11.1      # Versió actualitzada a la data actual
  diacritic: ^0.1.3
  english_words: ^4.0.0
  provider: ^6.0.0
  path_provider: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true