// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxfl4G2aI2rQaZOQmPkDfnPjGY-nDF6LU',
    appId: '1:95277363870:web:af50d572dffd0a1338c18f',
    messagingSenderId: '95277363870',
    projectId: 'charged-sum-419213',
    authDomain: 'charged-sum-419213.firebaseapp.com',
    storageBucket: 'charged-sum-419213.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASiSwpxx6FGssF4An2mYzmTP4OKKpsUIU',
    appId: '1:95277363870:android:1189d2f1abff860038c18f',
    messagingSenderId: '95277363870',
    projectId: 'charged-sum-419213',
    storageBucket: 'charged-sum-419213.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEsPPxySM7Ek2T_2tHbsp3g9nSKL_ix94',
    appId: '1:95277363870:ios:7c223b5ce056905e38c18f',
    messagingSenderId: '95277363870',
    projectId: 'charged-sum-419213',
    storageBucket: 'charged-sum-419213.firebasestorage.app',
    iosBundleId: 'com.example.numerologia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEsPPxySM7Ek2T_2tHbsp3g9nSKL_ix94',
    appId: '1:95277363870:ios:7c223b5ce056905e38c18f',
    messagingSenderId: '95277363870',
    projectId: 'charged-sum-419213',
    storageBucket: 'charged-sum-419213.firebasestorage.app',
    iosBundleId: 'com.example.numerologia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxfl4G2aI2rQaZOQmPkDfnPjGY-nDF6LU',
    appId: '1:95277363870:web:04c10266f5e21f3338c18f',
    messagingSenderId: '95277363870',
    projectId: 'charged-sum-419213',
    authDomain: 'charged-sum-419213.firebaseapp.com',
    storageBucket: 'charged-sum-419213.firebasestorage.app',
  );
}
