// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ2tW66EVN8uy1IHtiJ0YL2sV_tc2vUgo',
    appId: '1:477029872399:web:d8f3de435f429000a1847a',
    messagingSenderId: '477029872399',
    projectId: 'gen-lang-client-0094093679',
    authDomain: 'gen-lang-client-0094093679.firebaseapp.com',
    storageBucket: 'gen-lang-client-0094093679.firebasestorage.app',
    measurementId: 'G-XGMTY7HSNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBKm5_d3ozXTrcVUq7m8Nx7MgP4IeCsx4',
    appId: '1:477029872399:android:1e0a4b9ec8866fe0a1847a',
    messagingSenderId: '477029872399',
    projectId: 'gen-lang-client-0094093679',
    storageBucket: 'gen-lang-client-0094093679.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPAxWFMcqIx6od2En2PO1BlNUneFNPboY',
    appId: '1:477029872399:ios:20dc37ba5b8d59d4a1847a',
    messagingSenderId: '477029872399',
    projectId: 'gen-lang-client-0094093679',
    storageBucket: 'gen-lang-client-0094093679.firebasestorage.app',
    iosBundleId: 'com.example.numerologia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPAxWFMcqIx6od2En2PO1BlNUneFNPboY',
    appId: '1:477029872399:ios:20dc37ba5b8d59d4a1847a',
    messagingSenderId: '477029872399',
    projectId: 'gen-lang-client-0094093679',
    storageBucket: 'gen-lang-client-0094093679.firebasestorage.app',
    iosBundleId: 'com.example.numerologia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ2tW66EVN8uy1IHtiJ0YL2sV_tc2vUgo',
    appId: '1:477029872399:web:3c26fe3b48f3472da1847a',
    messagingSenderId: '477029872399',
    projectId: 'gen-lang-client-0094093679',
    authDomain: 'gen-lang-client-0094093679.firebaseapp.com',
    storageBucket: 'gen-lang-client-0094093679.firebasestorage.app',
    measurementId: 'G-XT4EJH5DT0',
  );
}
